/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package me.xingzhou.projects.simple.event.store

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
